export const recentRides = [
  {
    ride_id: "1",
    origin_address: "Delhi, India",
    destination_address: "Agra, India",
    origin_latitude: 28.6139,
    origin_longitude: 77.2090,
    destination_latitude: 27.1767,
    destination_longitude: 78.0081,
    ride_time: 180,
    fare_price: "1200.00",
    payment_status: "paid",
    driver_id: 2,
    user_id: "1",
    created_at: "2024-08-12 05:19:20.620007",
    driver: {
      driver_id: "2",
      first_name: "David",
      last_name: "Brown",
      profile_image_url: "",
      car_image_url: "",
      car_seats: 4,
      rating: "4.8",
    },
  },
  {
    ride_id: "2",
    origin_address: "Mumbai, India",
    destination_address: "Pune, India",
    origin_latitude: "19.0760",
    origin_longitude: "72.8777",
    destination_latitude: "18.5204",
    destination_longitude: "73.8567",
    ride_time: 150,
    fare_price: "1000.00",
    payment_status: "pending",
    driver_id: 3,
    user_id: "2",
    created_at: "2024-08-15 14:05:10.432112",
    driver: {
      driver_id: "3",
      first_name: "Michael",
      last_name: "Johnson",
      profile_image_url: "",
      car_image_url: "",
      car_seats: 4,
      rating: "4.5",
    },
  },
  {
    ride_id: "3",
    origin_address: "Bangalore, India",
    destination_address: "Mysore, India",
    origin_latitude: "12.9716",
    origin_longitude: "77.5946",
    destination_latitude: "12.2958",
    destination_longitude: "76.6394",
    ride_time: 180,
    fare_price: "950.00",
    payment_status: "paid",
    driver_id: 4,
    user_id: "3",
    created_at: "2024-08-18 10:22:45.789001",
    driver: {
      driver_id: "4",
      first_name: "Robert",
      last_name: "Smith",
      profile_image_url: "",
      car_image_url: "",
      car_seats: 6,
      rating: "4.9",
    },
  },
  {
    ride_id: "4",
    origin_address: "Chennai, India",
    destination_address: "Coimbatore, India",
    origin_latitude: "13.0827",
    origin_longitude: "80.2707",
    destination_latitude: "11.0168",
    destination_longitude: "76.9558",
    ride_time: 210,
    fare_price: "1250.00",
    payment_status: "paid",
    driver_id: 5,
    user_id: "4",
    created_at: "2024-08-20 08:30:15.654321",
    driver: {
      driver_id: "5",
      first_name: "James",
      last_name: "Williams",
      profile_image_url: "",
      car_image_url: "",
      car_seats: 4,
      rating: "4.6",
    },
  },
  {
    ride_id: "5",
    origin_address: "Kolkata, India",
    destination_address: "Darjeeling, India",
    origin_latitude: "22.5726",
    origin_longitude: "88.3639",
    destination_latitude: "27.0410",
    destination_longitude: "88.2636",
    ride_time: 300,
    fare_price: "1800.00",
    payment_status: "pending",
    driver_id: 6,
    user_id: "5",
    created_at: "2024-08-22 17:45:00.234567",
    driver: {
      driver_id: "6",
      first_name: "William",
      last_name: "Taylor",
      profile_image_url: "",
      car_image_url: "",
      car_seats: 4,
      rating: "4.7",
    },
  },
  {
    ride_id: "6",
    origin_address: "Jaipur, India",
    destination_address: "Udaipur, India",
    origin_latitude: "26.9124",
    origin_longitude: "75.7873",
    destination_latitude: "24.5854",
    destination_longitude: "73.7125",
    ride_time: 270,
    fare_price: "1600.00",
    payment_status: "paid",
    driver_id: 3, // Same driver as ride_id 2
    user_id: "6",
    created_at: "2024-08-25 12:10:30.111111",
    driver: {
      driver_id: "3",
      first_name: "Michael",
      last_name: "Johnson",
      profile_image_url: "",
      car_image_url: "",
      car_seats: 4,
      rating: "4.5",
    },
  },
  {
    ride_id: "7",
    origin_address: "Hyderabad, India",
    destination_address: "Vijayawada, India",
    origin_latitude: "17.3850",
    origin_longitude: "78.4867",
    destination_latitude: "16.5062",
    destination_longitude: "80.6480",
    ride_time: 200,
    fare_price: "1400.00",
    payment_status: "pending",
    driver_id: 5, // Same driver as ride_id 4
    user_id: "7",
    created_at: "2024-08-28 09:20:50.987654",
    driver: {
      driver_id: "5",
      first_name: "James",
      last_name: "Williams",
      profile_image_url: "",
      car_image_url: "",
      car_seats: 4,
      rating: "4.6",
    },
  },
];
